version: "3"

services:

  fluentd:
    container_name: fluentd
    restart: "no"
    image: fluent/fluentd:v1.2.5-onbuild
    volumes:
      - $PWD:/fluentd/etc
      - /tmp/test_log:/tmp/test_log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - test_net

  app:
    container_name: app
    restart: "no"
    build: .
    ports:
      - "3000:3000"
    networks:
      - test_net
    depends_on:
      - fluentd
    environment:
      - DEBUG
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        # fluentd-buffer-limit: "200MB"
        fluentd-address: "0.0.0.0:24224"
        tag: docker

networks:
  test_net:
    driver: bridge
